sudo: required
services:
  - docker

before_install:
  - docker build -t agc11/docker-react-course -f Dockerfile.dev .

script:
  - docker run agc11/docker-react-course npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-course"
  env: "DockerCourse-env"
  bucket_name: "elasticbeanstalk-us-east-1-712919848738"
  bucket_path: "docker-course"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
